development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL_LOCAL") %>
  channel_prefix: Mounter_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: Mounter_production
